
# Documentation: https://www.appveyor.com/docs/
#                https://www.appveyor.com/docs/installed-software/

image:
  - Visual Studio 2019

version: "{build}"
clone_depth: 1

# scripts that are called at very beginning, before repo cloning
init:
- git config --global core.longpaths true
- git config --global core.autocrlf input

branches:
  only:
     - javaUI
     - appveyor

environment:
 ANT_HOME: C:\apache-ant-1.10.8
 JAVA_HOME: C:\Program Files\Java\jdk1.8.0
 PLM_VERSION: 2.9.1

install:
  - cmd: if not exist %ANT_HOME% pushd . && cd \ && appveyor DownloadFile https://downloads.apache.org/ant/binaries/apache-ant-1.10.8-bin.zip && 7z x apache-ant-1.10.8-bin.zip && popd
  - set PATH=%ANT_HOME%\bin;%PATH%
  - cmd: if not exist c:\java-1.8.0-openjdk-1.8.0.252-2.b09.ojdkbuild.windows.x86_64.zip pushd . && cd \ && appveyor DownloadFile https://github.com/ojdkbuild/ojdkbuild/releases/download/java-1.8.0-openjdk-1.8.0.252-2.b09/java-1.8.0-openjdk-1.8.0.252-2.b09.ojdkbuild.windows.x86_64.zip && popd
  - cmd: if not exist c:\OpenJDK8U-jdk_x64_mac_hotspot_8u252b09.zip pushd . && cd \ && appveyor DownloadFile http://people.irisa.fr/Martin.Quinson/Teaching/PLM/OpenJDK8U-jdk_x64_mac_hotspot_8u252b09.zip && popd
  - cmd: if not exist c:\packr.jar pushd . && cd \ && appveyor DownloadFile https://libgdx.badlogicgames.com/ci/packr/packr.jar && popd

cache:
  - C:\apache-ant-1.10.8
  - C:\apache-ant-1.10.8-bin.zip
  - C:\java-1.8.0-openjdk-1.8.0.252-2.b09.ojdkbuild.windows.x86_64.zip
  - C:\OpenJDK8U-jdk_x64_mac_hotspot_8u252b09.zip
  - C:\packr.jar

build_script:
  - C:\apache-ant-1.10.8\bin\ant dist
  - java -jar c:\packr.jar --output plm-editor-%PLM_VERSION% --classpath dist\plm-%PLM_VERSION%*.jar --verbose --platform windows64 --jdk c:\java-1.8.0-openjdk-1.8.0.252-2.b09.ojdkbuild.windows.x86_64.zip --executable plm-map-editor --mainclass plm.core.ui.editor.buggleeditor.MapEditorApp
  - java -jar c:\packr.jar --output plm-%PLM_VERSION% --classpath dist\plm-%PLM_VERSION%*.jar --verbose --platform windows64 --jdk c:\java-1.8.0-openjdk-1.8.0.252-2.b09.ojdkbuild.windows.x86_64.zip --executable plm --mainclass plm.core.ui.ProgrammersLearningMachine 
  - cp plm-editor-%PLM_VERSION%/plm-map-editor.exe
  - 7z a plm-windows-%PLM_VERSION%.zip plm-%PLM_VERSION%
  - rd /s /q plm-%PLM_VERSION% # remove that directory
  - java -jar c:\packr.jar --output plm-editor-%PLM_VERSION% --classpath dist\plm-%PLM_VERSION%*.jar --verbose --platform mac --jdk C:\OpenJDK8U-jdk_x64_mac_hotspot_8u252b09.zip --executable plm-map-editor --mainclass plm.core.ui.editor.buggleeditor.MapEditorApp
  - java -jar c:\packr.jar --output plm-%PLM_VERSION% --classpath dist\plm-%PLM_VERSION%*.jar --verbose --platform mac --jdk C:\OpenJDK8U-jdk_x64_mac_hotspot_8u252b09.zip --executable plm --mainclass plm.core.ui.ProgrammersLearningMachine
  - cp plm-editor-%PLM_VERSION%/Contents/MacOS/plm-map-editor plm-%PLM_VERSION%/Contents/MacOS/plm-map-editor
  - 7z a plm-mac-%PLM_VERSION%.zip plm-%PLM_VERSION%

artifacts:
- path: dist\*.jar
  name: jarfile
- path: plm-windows-%PLM_VERSION%.zip
  name: plm-windows.zip
- path: plm-mac-%PLM_VERSION%.zip
  name: plm-mac.zip
