
# Documentation: https://www.appveyor.com/docs/
#                https://www.appveyor.com/docs/installed-software/

image:
  - Visual Studio 2019

version: "{build}"
clone_depth: 1

# scripts that are called at very beginning, before repo cloning
init:
- git config --global core.longpaths true
- git config --global core.autocrlf input

branches:
  only:
     - javaUI
     - appveyor

environment:
 ANT_HOME: C:\apache-ant-1.10.1
 JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
 - cmd: if not exist %ANT_HOME% pushd . && cd \ && appveyor DownloadFile https://downloads.apache.org/ant/binaries/apache-ant-1.10.8-bin.zip && 7z x apache-ant-1.10.8-bin.zip && popd
cache:
- C:\apache-ant-1.10.1

build_script:
- %ANT_HOME%\bin\ant dist

artifacts:
- path: dist\*.jar
  name: jarfile
