# This file is used to scan the project for issues automatically
# Browse the result here: https://sonarcloud.io/project/overview?id=BuggleInc_PLM

sonar.organization=buggleinc
sonar.projectKey=BuggleInc_PLM
sonar.projectName=Programmer's Learning Machine
sonar.projectVersion=2.9.3.1

sonar.links.homepage=https://people.irisa.fr/Martin.Quinson/Teaching/PLM/
sonar.links.issue=https://github.com/BuggleInc/PLM/issues
sonar.links.scm=https://github.com/BuggleInc/PLM/
# Comma-separated paths to directories with sources (required)
sonar.sources=src


# Disable some rules on some files
sonar.issue.ignore.multicriteria=j1

# Debugging features should not be enabled in production to not leak information
# but an open-source project has nothing to hide
sonar.issue.ignore.multicriteria.j1.ruleKey=java:S4507
sonar.issue.ignore.multicriteria.j1.resourceKey=src/**/*.java

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Version of the used prog languages
sonar.java.source=12
sonar.java.libraries=
sonar.python.version=3

# Exclude the exercise correction from the duplication detection.
# Examples are expected to be somehow repetitive
sonar.cpd.exclusions=src/**/*Entity.java