package jlm.core;

public enum GameState {

	IDLE, 
	SAVING, SAVING_DONE,
	LOADING, LOADING_DONE,
	COMPILATION_STARTED, COMPILATION_ENDED, 
	EXECUTION_STARTED, EXECUTION_ENDED,
	DEMO_STARTED, DEMO_ENDED,
}
