package plm.core.lang;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import plm.core.PLMCompilerException;
import plm.core.model.lesson.Exercise;
import plm.core.model.lesson.Exercise.StudentOrCorrection;
import plm.core.model.session.SourceFile;
import plm.universe.Entity;

/**
 * Ancestor of the languages whose student code is generated by injecting extracted pieces of the student/correction
 * source (the run() method, its dependencies, its imports...) into a language-specific template, then compiled and run
 * as an external process.
 */
public abstract class TemplatedRemoteLang extends RemoteExecutionLang {

  public TemplatedRemoteLang(String lang, String ext, ImageIcon i) { super(lang, ext, i); }

  /**
   * Extract every section of {@code code} delimited by a (possibly repeated) {@code beginMarker}/{@code endMarker}
   * pair, concatenated with a newline after each occurrence. Used to pull out the "/* BEGIN DEPENDENCY *&#47;
   * ... /* END DEPENDENCY *&#47;"-style sections that Java and Scala exercises use to mark code the template must
   * carry over verbatim (dependencies, extra imports).
   */
  protected static String extractMarkedSection(String code, String beginMarker, String endMarker)
  {
    StringBuilder section = new StringBuilder();
    for (int i = 0; i < code.length(); i++) {
      if (!code.startsWith(beginMarker, i))
        continue;
      int begin = i + beginMarker.length();
      int end   = code.indexOf(endMarker, i);
      section.append(code, begin, end).append("\n");
      i = end + endMarker.length();
    }
    return section.toString();
  }

  /**
   * Common to Java, Scala and Python: {@code compileExo} stores the path of the compiled/generated entry point in
   * {@code sf.meta.get(getLang().toUpperCase())} (e.g. "JAVA", "SCALA", "PYTHON"); mutating an entity just means
   * copying that path onto it so that {@code runEntity} can later spawn the right process.
   */
  @Override public ArrayList<Entity> mutateEntities(Exercise exo, List<Entity> olds, StudentOrCorrection whatToMutate) throws PLMCompilerException
  {
    List<SourceFile> sourceFiles = exo.getSourceFilesList(this);

    if (sourceFiles.size() != 1)
      throw new IllegalStateException("ToBeYetImplemented: Cannot differentiate entity scripts for now.");

    String path = sourceFiles.get(0).meta.get(getLang().toUpperCase());
    if (path != null)
      for (Entity old : olds)
        old.setScript(this, path);

    return new ArrayList<>(olds);
  }

  /* to make sure that the subsequent version of the same class have different names, in order to bypass the cache of the class loader */
  /* FIXME: the exercise ID should be used now that the student code is executed in a remote process. There is no class cache to bypass anymore */
  protected static final String packageNamePrefix = "plm.runtime";
  protected int packageNameSuffix                 = 0;
  protected String packageName() { return packageNamePrefix + packageNameSuffix; }
}
