# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ javaUI ]
  pull_request:
    branches: [ javaUI ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ryankurte/action-apt@v0.3.0
      with:
        packages: "gettext po4a"
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Test exercise solutions (Ant)
      run: ant -noinput -buildfile build.xml test-exos
    - name: Unit tests (Ant)
      run: ant -noinput -buildfile build.xml test-unit
    - name: Integration tests (Ant)
      run: ant -noinput -buildfile build.xml test-integration
    - name: Build jarfile (Ant)
      run: ant -noinput -buildfile build.xml dist
